name: Build Android .so

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Android NDK
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r25b

      - name: Build with NDK
        run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-so-library
          path: libs/
